### PR TITLE
Updated how we handle our list for the Search Feature

### PR DESCRIPTION
**Pull request by KyletheWolff**
#12 , #6: Updated the custom listView to the JavaFX standard listView

And created the custom cell to go with the new listView.

Changes: 
1. Updated the listView
2. Created the custom cell
3. Hooked up the Nutrition Label code to the new custom cell 
4. Deleted the old code that was not needed anymore

### CODE REVIEW

**Comment by BrandonVanderMey** [comment]
I will look at this in detail tonight.

**Comment by KyletheWolff** [comment]
Assignee is the person who reviews the PR

**Comment by BrandonVanderMey** [comment]
Haha, I thought it was the other way around.  I thought it was whomever was working on that particular issue.

**Comment by KyletheWolff** [comment]
That would be the assignee on the issue :)

**Comment by BrandonVanderMey** [comment]
In CustomSearchCell.fxml, was there a reason to not use a <root> tag?
In the Style class, where is this used?  Is it useful?  It's fine if it's there, I'm just curious why you made this.
Other than that, everything looks great.

**Comment by KyletheWolff** [comment]
No tag needed since that is a custom cell that gets placed in the listView. Since we extend ListCell<DetailData> it is just a cell that is customized.

**Comment by BrandonVanderMey** [comment]
How does extending the ListCell class help us accomplish not needing a root tag?

**Comment by KyletheWolff** [comment]
I am not taking the customCell and placing it into the SearchListFrameController. 

In the cellfactory for the listView is where the cell object is made. 

No need for a root tag since we are not placing the cell in the another FXML file.

**Comment by BrandonVanderMey** [comment]
Oh I see now.  Makes perfect sense.  Thank you for clearing that up!  Merged.  But as a side question, what was the reason for the Style Class?

**Pull request merged**
